[profile.default]
src = "contracts/src"
test = "contracts/tests"
script = "contracts/scripts"
out = "contracts/out"
cache_path = "contracts/cache"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options